[package]
name = "rust-irc"
version = "0.1.0"
authors = ["John Children <john@cognitivelogic.com>"]

[dependencies]
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"

bytes = "0.4"
serde = "1.0"
serde_derive = "1.0"
rmp-serde = "0.13.4"
